### ISSUE TITLE
network or topology

### ISSUE THREAD

**Issue by rnrson9** [fabiocarminati/SD-WAN_Simulation#1]
Hello, I'm very interested and excited by this project, which uses Matlab to simulate an SDN scenario. I do not know what type of network scenario this is, but I can discern two paths. Could you add some network or topology diagrams, and are there any additional references for this simulation?

**Comment by fabiocarminati** [comment]
Hello, I simulated two virtual overlay paths: primary and backup. 
I was interested only in how the End-to-end delay of the existing connections flowing in one path were affected by a new custom communication. Therefore I didn't need to define an exact underlay topology (i.e. the actual network diagram)
